/* ----------------------------------------------------------------------------------------
	GLMVS - Map Library System

	This file is to add the library of all the maps you're registering for,
	it uses a super easy format for everyone to follow and contribute for
	GLMVS. It is undesirable to add maps you're not going to use for the library.
	But you can add as many as you please (until lua hangs itself).

	Format to add maps in the library:
	GLMVS.AddToLibrary( mapname, [plreq], { realname, author, description } )
---------------------------------------------------------------------------------------- */

GLMVS.AddToLibrary("de_dolls", {"Dolls"})
GLMVS.AddToLibrary("cs_rat_cuisine_b1", {"Rat Cuisine"})
GLMVS.AddToLibrary("ttt_67thway_v3", {"67th Way v3"})
-- GLMVS.AddToLibrary("ttt_67thway_v4", {"67th Way v4"})
GLMVS.AddToLibrary("ttt_airbus_b3", {"Airbus"})
GLMVS.AddToLibrary("ttt_bank_b3", {"Bank"})
GLMVS.AddToLibrary("ttt_borders", {"Borders"})
GLMVS.AddToLibrary("ttt_canyon_a4", {"Canyon"})
GLMVS.AddToLibrary("ttt_chaser_v2", {"Chaser"})
GLMVS.AddToLibrary("ttt_christmas_pool_v1a", {"Christmas Pool"})
GLMVS.AddToLibrary("ttt_clue", {"Clue"})
GLMVS.AddToLibrary("ttt_community_pool", {"Community Pool"})
GLMVS.AddToLibrary("ttt_concentration_b2", {"Concentration"})
GLMVS.AddToLibrary("ttt_cruise", {"Cruise"})
GLMVS.AddToLibrary("ttt_crummycradle_a4", {"Crummy Cradle"})
GLMVS.AddToLibrary("ttt_eek_v6", {"EEK!"})
GLMVS.AddToLibrary("ttt_ferrostruct", {"Ferrostruct"})
GLMVS.AddToLibrary("ttt_floodlights", {"Flood Lights"})
GLMVS.AddToLibrary("ttt_lordcharles_mansion_v3", {"Lord Charles Mansion"})
GLMVS.AddToLibrary("ttt_lost_temple_v2", {"Lost Temple"})
--GLMVS.AddToLibrary("ttt_lttp_kakariko_b1", {"Kakariko"}) -- crashes server
GLMVS.AddToLibrary("ttt_main_street_b3a", {"Main Street"})
GLMVS.AddToLibrary("ttt_mc_skyislands", {"Minecraft Sky Isles"})
GLMVS.AddToLibrary("ttt_minecraft_b5", {"Minecraft"})
GLMVS.AddToLibrary("ttt_plaza_b6", {"Plaza"})
GLMVS.AddToLibrary("ttt_rapture", {"Rapture"})
GLMVS.AddToLibrary("ttt_ratistry", {"Ratistry"})
GLMVS.AddToLibrary("ttt_richland", {"Richland"})
GLMVS.AddToLibrary("ttt_rooftops_a2", {"Rooftops"})
GLMVS.AddToLibrary("ttt_roy_the_ship", {"Roy The Ship"})
GLMVS.AddToLibrary("ttt_scarisland_b1", {"Scar Island"})
GLMVS.AddToLibrary("ttt_schooldayv2", {"School Day"})
GLMVS.AddToLibrary("ttt_skytower_b1-1", {"Sky Tower"})
GLMVS.AddToLibrary("ttt_slender_v2", {"Slender"})
GLMVS.AddToLibrary("ttt_stadium", {"Stadium"})
GLMVS.AddToLibrary("ttt_summermansion_b2", {"Summer Mansion"})
GLMVS.AddToLibrary("ttt_terrorception", {"Terrorception"})
GLMVS.AddToLibrary("ttt_terrortrainb2", {"Terror Train"})
GLMVS.AddToLibrary("ttt_thepit", {"The Pit"})
GLMVS.AddToLibrary("ttt_urban_ruins_v1", {"Urban Ruins"})
GLMVS.AddToLibrary("ttt_whitehouse_b2", {"Whitehouse"})

GLMVS.AddToLibrary("ttt_aircraft_v1b", {"Aircraft"})
GLMVS.AddToLibrary("ttt_amsterville", {"Amsterville"})
GLMVS.AddToLibrary("ttt_bb_canalwarehousev2_r3", {"Canal Warehouse"})
GLMVS.AddToLibrary("ttt_bb_outpost57_b5", {"Outpost 57"})
GLMVS.AddToLibrary("ttt_bb_suburbia_b3", {"Suburbia"})
GLMVS.AddToLibrary("ttt_bb_teenroom_b2", {"Teen Room"})
GLMVS.AddToLibrary("ttt_bunker", {"Bunker"})
GLMVS.AddToLibrary("ttt_camel_v1", {"Camel"})
GLMVS.AddToLibrary("ttt_casino_b2", {"Casino"})
GLMVS.AddToLibrary("ttt_christmastown", {"Christmas Town"})
GLMVS.AddToLibrary("ttt_cluedo_b5", {"Cluedo"})
--GLMVS.AddToLibrary("ttt_comancher_censored", {"Comancher"}) -- no guns
GLMVS.AddToLibrary("ttt_community_bowling_v5a", {"Community Bowling"})
GLMVS.AddToLibrary("ttt_cyberia_a3", {"Cyberia"})
GLMVS.AddToLibrary("ttt_district_a4", {"District"})
GLMVS.AddToLibrary("ttt_enclave_b1", {"Enclave"})
GLMVS.AddToLibrary("ttt_fastfood_a6", {"Fast Food"})
GLMVS.AddToLibrary("ttt_forest_final", {"Forest"})
GLMVS.AddToLibrary("ttt_forgotten_forge", {"Forgotten Forge"})
GLMVS.AddToLibrary("ttt_foundation_a1", {"Foundation"})
GLMVS.AddToLibrary("ttt_lunar_base_v2a", {"Lunar Base"})
GLMVS.AddToLibrary("ttt_mars_colony_a1", {"Mars Colony"})
GLMVS.AddToLibrary("ttt_metropolis", {"Metropolis"})
GLMVS.AddToLibrary("ttt_minecraftcity_v4", {"Minecraft City"})

GLMVS.AddToLibrary("ttt_mw2_rust", {"MW2 Rust"})

-- GLMVS.AddToLibrary("ttt_glacier", {"Glacier"})
GLMVS.AddToLibrary("ttt_horizon_v1", {"Horizon"})
GLMVS.AddToLibrary("ttt_skyscraper", {"Skyscraper"})
GLMVS.AddToLibrary("ttt_equilibre", {"Equilibre"})

GLMVS.AddToLibrary("ttt_waterworld", {"Waterworld"})
GLMVS.AddToLibrary("ttt_island_2013", {"Island 2013"})
GLMVS.AddToLibrary("ttt_lego", {"Lego"})
GLMVS.AddToLibrary("ttt_minecraft_haven", {"Minecraft Haven"})
GLMVS.AddToLibrary("ttt_nightfever", {"Night Fever"})
GLMVS.AddToLibrary("ttt_parkhouse", {"Park House"})
GLMVS.AddToLibrary("ttt_starfish_island_v1_2", {"Starfish Island"})
